{
    "id":497084294,
    "body":"$SAVA stop loss raid this afternoon was great buying opportunity loaded shares under $30!",
    "created_at":"2022-11-18T21:17:30Z",
    "user":{
       "id":3011634,
       "username":"CaymanSlushFund",
       "name":"Cayman Slush Fund",
       "avatar_url":"https://avatars.stocktwits.com/production/3011634/thumb-1578414526.png",
       "avatar_url_ssl":"https://avatars.stocktwits.com/production/3011634/thumb-1578414526.png",
       "join_date":"2020-01-07",
       "official":false,
       "identity":"User",
       "classification":[
          
       ],
       "search_regions":[
          
       ],
       "followers":296,
       "following":473,
       "ideas":1935,
       "watchlist_stocks_count":178,
       "like_count":946,
       "plus_tier":"",
       "premium_room":"",
       "trade_app":false,
       "trade_status":"PENDING_MFA",
       "subscribers_count":39,
       "subscribed_to_count":55,
       "following_stocks":0,
       "location":"",
       "bio":"None",
       "website_url":"None",
       "trading_strategy":{
          "assets_frequently_traded":[
             "Equities",
             "Options"
          ],
          "approach":"Growth",
          "holding_period":"Day Trader",
          "experience":"Professional"
       }
    },
    "source":{
       "id":1149,
       "title":"StockTwits for iOS",
       "url":"http://www.stocktwits.com/mobile"
    },
    "symbols":[
       {
          "id":3258,
          "symbol":"SAVA",
          "title":"Cassava Sciences Inc",
          "aliases":[
             "PTIE"
          ],
          "is_following":false,
          "watchlist_count":49085,
          "has_pricing":true,
          "exchange":"NASDAQ",
          "sector":"HealthTechnology",
          "industry":"Biotechnology",
          "logo_url":"http://logos.xignite.com/NASDAQGM/00048445.gif",
          "trending":false,
          "trending_score":0.491283,
          "trade_status":"FRACTIONAL"
       }
    ],
    "prices":[
       {
          "id":3258,
          "symbol":"SAVA",
          "price":"33.12",
          "current_price":"35.74",
          "change_since_message":"2.62",
          "percent_change_since_message":"7.91",
          "exchange":"NASDAQ"
       }
    ],
    "likes":{
       "total":3,
       "recent":[
          {
             "id":1717498,
             "username":"Cutlass",
             "name":"Rachel Martens",
             "avatar_url":"https://avatars.stocktwits.com/production/1717498/thumb-1596491532.png?1596491532",
             "avatar_url_ssl":"https://avatars.stocktwits.com/production/1717498/thumb-1596491532.png?1596491532"
          },
          {
             "id":199830,
             "username":"LifeSVR",
             "name":"DavidD",
             "avatar_url":"https://avatars.stocktwits.com/production/199830/thumb-1354913676.png?1354913676",
             "avatar_url_ssl":"https://avatars.stocktwits.com/production/199830/thumb-1354913676.png?1354913676"
          },
          {
             "id":6322901,
             "username":"Mattyice81",
             "name":"Matt",
             "avatar_url":"https://avatars.stocktwits.com/images/default_avatar_thumb.jpg",
             "avatar_url_ssl":"https://avatars.stocktwits.com/images/default_avatar_thumb.jpg"
          }
       ],
       "user_ids":[
          1717498,
          6322901,
          199830
       ]
    },
    "mentioned_users":[
       
    ],
    "entities":{
       "sentiment":{
          "basic":"Bullish"
       }
    }
 }